"""Models for the ParNeeds validation workflows."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import Optional


@dataclass(frozen=True)
class ParNeedsConfig:
    """Configuration for one ParNeeds validation run."""

    strategy: str
    timeframe: str = "5m"
    timerange: Optional[str] = None
    pairs: list[str] = field(default_factory=list)
    dry_run_wallet: float = 80.0
    max_open_trades: int = 2
    seed: int = 20240101


@dataclass(frozen=True)
class ParNeedsWindow:
    """One backtest window generated by a ParNeeds workflow."""

    timerange: str
    start: date
    end: date
    days: int
    label: str


@dataclass(frozen=True)
class CandleCoverageReport:
    """Coverage status for one pair/timeframe/timerange."""

    pair: str
    timeframe: str
    timerange: str
    first_candle: str = ""
    last_candle: str = ""
    expected_candles: int = 0
    actual_candles: int = 0
    gap_count: int = 0
    missing_reasons: list[str] = field(default_factory=list)

    @property
    def is_complete(self) -> bool:
        """Return True when the requested candle range appears complete."""
        return not self.missing_reasons


@dataclass(frozen=True)
class ParNeedsRunResult:
    """Displayable result for a completed ParNeeds backtest window."""

    timerange: str
    status: str
    run_id: str = ""
    profit_total_pct: Optional[float] = None
    win_rate_pct: Optional[float] = None
    max_drawdown_pct: Optional[float] = None
    trades_count: Optional[int] = None
